version: '3'

networks:
  visual-limes-net:
    external: false

volumes:
  activemq-data: { }

services:

  faros-backend:
    container_name: faros-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Denv=test -jar app.jar" ]
    ports:
      - "9095:9090"
    env_file:
      - .env
    tty: true
    networks:
      - visual-limes-net

  hl7-listener:
    container_name: hl7-listener
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Denv=test -jar app.jar integraciones adt_listener" ]
    ports:
      - "49721:49721"
    env_file:
      - .env
    tty: true
    networks:
      - visual-limes-net
  hl7-listener-dev:
    container_name: hl7-listener-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: [ "sh", "-c", "java $JAVA_OPTS -Denv=docker -jar app.jar integraciones adt_listener" ]
    ports:
      - "49721:49721"
    env_file:
      - .env
    tty: true
    networks:
      - visual-limes-net

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secreto
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS prescripciones;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    networks:
      - visual-limes-net

  firebird:
    container_name: firebird
    restart: always
    image: controlsoft/firebird
    ports:
      - 3050:3050
      - 3051:3051
    volumes:
      - C:\databases:/databases # Windows
      #- /home/user/databases:/databases # Linux
    environment:
      - PASSWORD=masterkey
    networks:
      - visual-limes-net

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.9.14-management'
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=master
      - RABBITMQ_DEFAULT_PASS=conejito
    networks:
      - visual-limes-net

  activemq:
    container_name: activemq.sh
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5673:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [ visual-limes-net ]
    volumes: [ "activemq.sh-data:/opt/activemq.sh/conf", "activemq.sh-data:/data/activemq.sh", "activemq.sh-data:/var/log/activemq.sh" ]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

